"use client";
import { useRef, useState } from "react";

type Result = { summary: string; goals: { domain: string; text: string; baseline?: string; criterion?: string }[]; services: string; accommodations: string[] };
export function DocumentUploader({ clientId, clientName }: { clientId: string; clientName: string }) {
  const input = useRef<HTMLInputElement>(null); const [status, setStatus] = useState<"idle"|"uploading"|"done"|"error">("idle"); const [result, setResult] = useState<Result>(); const [kept, setKept] = useState<Record<number, boolean>>({}); const [error, setError] = useState("");
  async function upload(file?: File) { if (!file) return; setStatus("uploading"); const data = new FormData(); data.set("file", file); data.set("clientId", clientId); data.set("clientName", clientName); try { const response = await fetch("/api/documents", { method: "POST", body: data }); const json = await response.json(); if (!response.ok) throw new Error(json.error); setResult(json); setStatus("done"); } catch (e) { setError(e instanceof Error ? e.message : "Upload failed"); setStatus("error"); } }
  async function keepGoals(event: React.FormEvent) { event.preventDefault(); if (!result) return; setError(""); const response = await fetch(`/api/clients/${clientId}/goals`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ goals: result.goals.map((goal, index) => ({ ...goal, keep: kept[index] ?? true })) }) }); const json = await response.json(); if (!response.ok) { setError(json.error ?? "Could not save goals"); return; } setResult(undefined); }
  return <section className="data-card upload-card"><div className="upload-icon">⇧</div><h3>IEP or prior evaluation</h3><p>Upload a PDF and Sayso will draft goals for your review.</p><input ref={input} hidden type="file" accept="application/pdf" onChange={(e) => upload(e.target.files?.[0])}/><button className="soft-button wide-soft" disabled={status === "uploading"} onClick={() => input.current?.click()}>{status === "uploading" ? "Extracting securely…" : status === "done" ? "Upload another PDF" : "Choose PDF"}</button><small>PDF · up to 20 MB</small>{error && <p className="form-error">{error}</p>}{result && <form onSubmit={keepGoals} className="extract-result"><strong>Draft ready — therapist review</strong><p>{result.summary}</p>{result.goals.map((goal,index)=><label className="extracted-goal" key={`${goal.domain}-${index}`}><input type="checkbox" checked={kept[index]??true} onChange={(event)=>setKept({...kept,[index]:event.target.checked})}/><span><b>{goal.domain}</b>{goal.text}</span></label>)}<button className="soft-button wide-soft">Save kept goals</button></form>}</section>;
}
