"use client";
import { useState } from "react";
import { demoGoals } from "@/lib/demo";

declare global { interface Window { webkitSpeechRecognition?: new () => { lang: string; continuous: boolean; onresult: (event: { results: ArrayLike<{ 0: { transcript: string } }> }) => void; onend: () => void; start(): void; stop(): void } } }

export function SessionEditor({ appointmentId, clientName }: { appointmentId: string; clientName: string }) {
  const [ratings, setRatings] = useState<Record<string,number>>({}); const [comments, setComments] = useState<Record<string,string>>({}); const [notes,setNotes]=useState(""); const [clinical,setClinical]=useState(""); const [parent,setParent]=useState(""); const [practice,setPractice]=useState(""); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [listening,setListening]=useState(false); const [error,setError]=useState("");
  function dictate() { const Recognition = window.webkitSpeechRecognition; if (!Recognition) { setError("Dictation is not supported in this browser."); return; } const recognition = new Recognition(); recognition.lang="en-US"; recognition.continuous=true; recognition.onresult=(e)=>setNotes((value)=>`${value} ${e.results[e.results.length-1][0].transcript}`.trim()); recognition.onend=()=>setListening(false); setListening(true); recognition.start(); }
  async function generate() { setLoading(true); setError(""); try { const response=await fetch("/api/ai/session_summary",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({clientName,input:{goals:demoGoals.map(g=>({id:g.id,text:g.text,rating:ratings[g.id]})),notes,lastThreeSummaries:[]}})}); const result=await response.json(); if(!response.ok)throw new Error(result.error??"Generation failed"); setClinical(result.clinicalNote);setParent(result.parentSummary);setPractice(result.homePractice); } catch(e){ setError(e instanceof Error?e.message:"Generation failed"); } finally{setLoading(false);} }
  async function save() { setSaving(true); setError(""); const response = await fetch(`/api/appointments/${appointmentId}/session`, { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify({ noteText: clinical, parentSummaryText: practice ? `${parent}\n\nHome practice: ${practice}` : parent, progress: demoGoals.filter((goal) => ratings[goal.id]).map((goal) => ({ goalId: goal.id, rating: ratings[goal.id], comment: comments[goal.id] })) }) }); const result = await response.json(); setSaving(false); if (!response.ok) setError(result.error ?? "Could not save session"); else window.location.assign("/dashboard"); }
  return <div className="session-layout"><div><section className="data-card section-card"><div className="section-title"><div><h2>Goal check-in</h2><p>Rate today&apos;s performance. 1 = maximum support, 5 = independent.</p></div></div>{demoGoals.map((goal)=><div className="rating-row" key={goal.id}><div><span>{goal.domain}</span><p>{goal.text}</p></div><div className="rating-buttons">{[1,2,3,4,5].map(n=><button className={ratings[goal.id]===n?"selected":""} onClick={()=>setRatings({...ratings,[goal.id]:n})} key={n}>{n}</button>)}</div><input aria-label={`Comment for ${goal.domain}`} value={comments[goal.id] ?? ""} onChange={(event) => setComments({ ...comments, [goal.id]: event.target.value })} placeholder="Optional observation"/></div>)}</section><section className="data-card section-card notes-editor"><div className="section-title"><div><h2>Session notes</h2><p>Capture observations in your own words.</p></div><button className={listening?"dictating":"soft-button"} onClick={dictate}>◉ {listening?"Listening…":"Dictate"}</button></div><textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder="What did you work on? What cues helped? How did the client respond?"/>{error&&<p className="form-error">{error}</p>}<button className="ai-button" onClick={generate} disabled={loading}>✦ {loading?"Drafting summaries…":"Generate draft with AI"}</button></section></div><aside><section className="data-card draft-card"><span className="draft-label">AI DRAFT · REVIEW REQUIRED</span><h3>Clinical note</h3><textarea value={clinical} onChange={e=>setClinical(e.target.value)} placeholder="Generate a draft, then review and edit it here."/><h3>Parent-friendly summary</h3><textarea value={parent} onChange={e=>setParent(e.target.value)} placeholder="The family update will appear here."/><h3>Home practice</h3><textarea className="short" value={practice} onChange={e=>setPractice(e.target.value)} placeholder="One suggested activity."/><p className="safety-note">Nothing is saved or shared until you review it.</p><button className="primary wide" disabled={!clinical||!parent||saving} onClick={save}>{saving ? "Saving…" : "Save & send summary"}</button></section></aside></div>;
}
